import { useState } from 'react';
import { Clock, TrendingDown, TrendingUp, ChevronDown, ArrowRight } from 'lucide-react';

interface PricingModel {
  icon: React.ReactNode;
  title: string;
  shortDescription: string;
  details: string[];
  example: string;
  gradient: string;
}

const pricingModels: PricingModel[] = [
  {
    icon: <Clock className="w-10 h-10" />,
    title: 'Hourly Pricing',
    shortDescription: 'Pay only for the time required to build your automation.',
    details: [
      'Ideal for small projects and first collaborations',
      'Transparent hourly rate',
      'Final price depends on total hours required'
    ],
    example: '15 hours × $50/hour = $750',
    gradient: 'from-orange-400 to-orange-500'
  },
  {
    icon: <TrendingDown className="w-10 h-10" />,
    title: 'Cost-Saving Pricing',
    shortDescription: 'Pricing based on how much money the automation saves your business.',
    details: [
      'Best for companies with high operational costs',
      'You pay a percentage of the cost reduction',
      'Clear savings calculation before starting'
    ],
    example: 'If automation saves $40,000/year → client pays 10–25% of that amount',
    gradient: 'from-orange-500 to-orange-600'
  },
  {
    icon: <TrendingUp className="w-10 h-10" />,
    title: 'Revenue-Based Pricing (Rev Uplift)',
    shortDescription: 'Pay based on the extra revenue generated by the automation.',
    details: [
      'Ideal for lead generation, marketing, and sales automation',
      'Aligned with business growth',
      'Setup fee + percentage of new revenue generated'
    ],
    example: '$3,000 setup fee + 20% of new monthly revenue generated',
    gradient: 'from-orange-600 to-orange-700'
  }
];

export default function Pricing() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const toggleExpand = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  return (
    <section className="py-32 bg-white" id="pricing">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-20 animate-fade-in-up">
          <h2 className="text-5xl md:text-6xl font-bold text-black mb-6">
            Pricing <span className="gradient-text">Models</span>
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Flexible pricing options designed to match your business goals.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {pricingModels.map((model, index) => (
            <div
              key={index}
              className="group relative bg-white rounded-3xl p-8 shadow-xl hover:shadow-2xl transition-all duration-500 cursor-pointer border-2 border-gray-100 hover:border-orange-400 transform hover:-translate-y-2"
              onClick={() => toggleExpand(index)}
            >
              <div className="absolute top-0 right-0 w-40 h-40 bg-gradient-to-br from-orange-500/10 to-transparent rounded-bl-full opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

              <div className="relative z-10">
                <div className={`inline-flex p-4 rounded-2xl bg-gradient-to-br ${model.gradient} text-white mb-6 transform group-hover:scale-110 group-hover:rotate-3 transition-all duration-300 shadow-lg`}>
                  {model.icon}
                </div>

                <h3 className="text-2xl font-bold text-black mb-4 group-hover:gradient-text transition-all duration-300">
                  {model.title}
                </h3>

                <p className="text-gray-600 mb-6 leading-relaxed">
                  {model.shortDescription}
                </p>

                <div className="flex items-center justify-between text-orange-500 font-semibold mb-4">
                  <span className="text-sm flex items-center gap-2">
                    Learn More
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform duration-300" />
                  </span>
                  <ChevronDown
                    className={`w-5 h-5 transition-transform duration-300 ${
                      expandedIndex === index ? 'rotate-180' : ''
                    }`}
                  />
                </div>

                <div
                  className={`overflow-hidden transition-all duration-500 ${
                    expandedIndex === index ? 'max-h-[500px] opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <div className="border-t-2 border-gray-200 pt-6 space-y-6">
                    <div>
                      <h4 className="font-bold text-black mb-3 flex items-center gap-2">
                        <span className="w-2 h-2 bg-orange-500 rounded-full"></span>
                        Details:
                      </h4>
                      <ul className="space-y-2">
                        {model.details.map((detail, idx) => (
                          <li key={idx} className="flex items-start gap-3 text-gray-700">
                            <span className="text-orange-500 mt-1">•</span>
                            <span className="text-sm leading-relaxed">{detail}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className={`bg-gradient-to-br ${model.gradient} rounded-xl p-5 text-white shadow-lg`}>
                      <h4 className="font-bold mb-2 text-sm uppercase tracking-wide opacity-90">Example:</h4>
                      <p className="text-base font-semibold leading-relaxed">
                        {model.example}
                      </p>
                    </div>

                    <button className="w-full py-3 px-6 bg-black text-white font-semibold rounded-xl hover:bg-gradient-to-r hover:from-orange-500 hover:to-orange-600 transition-all duration-300 flex items-center justify-center gap-2 group/btn">
                      Get Started
                      <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform duration-300" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 text-center">
          <div className="inline-block bg-gradient-to-r from-orange-50 to-orange-100 rounded-2xl p-8 border-2 border-orange-200">
            <p className="text-lg text-gray-800 max-w-2xl">
              <span className="font-bold text-orange-600">Not sure which model fits?</span> We'll help you choose the best option during our consultation call.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
